name: Lint with mypy
on:
  push:
    paths:
      - .github/workflows/mypy-lint.yml
      - vim_eof_comment/*.pyi
      - vim_eof_comment/args/*.pyi
      - vim_eof_comment/comments/*.pyi
      - vim_eof_comment/types/*.pyi
    branches:
      - main
  pull_request:
    paths:
      - .github/workflows/mypy-lint.yml
      - vim_eof_comment/*.pyi
      - vim_eof_comment/args/*.pyi
      - vim_eof_comment/comments/*.pyi
      - vim_eof_comment/types/*.pyi
    branches:
      - main
jobs:
  mypy-lint:
    runs-on: ubuntu-latest
    name: Lint with mypy
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Python environment
        uses: actions/setup-python@v6.1.0
        with:
          python-version: "3.10"
          architecture: x64
      - name: Install mypy
        run: |
          pip install -U mypy mypy-extensions typying typing-extensions
      - name: Run mypy
        uses: sasanquaneuf/mypy-github-action@main
        with:
          checkName: mypy-lint # NOTE: this needs to be the same as the job name
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
